### Create a New Payment
POST http://localhost:8000/api/payments
Content-Type: application/json

{
  "phone": "0722227152",
  "amount": 5000,
  "status": "pending",
  "transactionId": "MPESA123456783",
  "merchantRequestId": "MERCHANT1234",
  "checkoutRequestId": "CHECKOUT451"
}

### Get All Payments
GET http://localhost:8000/api/payments
Content-Type: application/json

### Get a Single Payment by ID
GET http://localhost:8000/api/payments/1
Content-Type: application/json

### Update a Payment (Change Status)
PATCH http://localhost:8000/api/payments/1
Content-Type: application/json

{
  "status": "completed",
  "transactionId": "MPESA987654321"
}

### Delete a Payment
DELETE http://localhost:8000/api/payments/1
Content-Type: application/json


### Initiate Mpesa STK Push
POST http://localhost:8000/api/mpesa/stkpush
Content-Type: application/json

{
  "phone": "254722227154",
  "amount": 1
}

### Simulate Mpesa STK Callback
POST http://localhost:8000/api/mpesa/callback
Content-Type: application/json

{
  "Body": {
    "stkCallback": {
      "MerchantRequestID": "bbcd-4a89-bd1a-6ecdc639893b2273919",
      "CheckoutRequestID": "ws_CO_03022025130928186722227154",
      "ResultCode": "0",
      "ResultDesc": "Success. Request accepted for processing",
      "CallbackMetadata": {
        "Item": [
          { "Name": "MpesaReceiptNumber", "Value": "174379" },
          { "Name": "Amount", "Value": 1 },
          { "Name": "TransactionDate", "Value": "202502031530" },
          { "Name": "PhoneNumber", "Value": "0722227154" }
        ]
      }
    }
  }
}
